**NUMPY**

`numpy` es un módulo para trabajar con arrays, que son un tipo de lista, solo que mucho más rápidos de procesar.

El objeto array de `numpy` recibe el nombre de `ndarray`. Este tipo de dato es muy usado en el mundo de la ciencia de datos, donde la velocidad y los recursos son de gran importancia.

In [3]:
import numpy as np

Podemos comprobar la versión de `numpy` con la siguiente línea de código

In [4]:
print(np.__version__)

1.24.4


#### Creando arrays

Para crear un `ndarray` usamos el método `.array()`.

Lo podemos hacer a partir de una lista:

In [5]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [6]:
b = [1, 2, 3, 4, 5]
print(b)

[1, 2, 3, 4, 5]


In [8]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'list'>


Mientras que las listas pueden contener elementos de diversos tipos (números, cadenas, listas, etc) en una misma lista, los array de NumPy solo pueden contener elementos de un tipo, es decir son homogéneos.

Los elementos array de Numpy son más rápidos y compactos que las listas de Python, además consumen menos memoria.

In [9]:
import time
start = time.time()
# crear un array con numeros aleatorios
a = np.random.rand(1000000)
end = time.time()
tiempo1 = end - start
print(f"El tiempo que demora en generar un array: {tiempo1} segundos")

# crear una lista con numeros aleatorios
start = time.time()
b = [np.random.rand() for i in range(1000000)]
end = time.time()
tiempo2 = end - start
print(f"El tiempo que demora en generar una lista: {tiempo2} segundos")

tiempo2 / tiempo1

El tiempo que demora en generar un array: 0.010563850402832031 segundos
El tiempo que demora en generar una lista: 0.48201823234558105 segundos


45.62902861785682

### Elementos de un array


#### Caso unidimensional

Podemos acceder a los elementos de un array con la sintaxis `[]`.

**Observación.** Recordad que en `Python` los índices empezaban en 0

In [10]:
a = np.array([2, 3, 4, 5, 6])
print(a)

print(f"Primer elemento = {a[0]}")
print(f"Segundo elemento = {a[1]}")
print(f"Último elemento = {a[-1]}")

[2 3 4 5 6]
Primer elemento = 2
Segundo elemento = 3
Último elemento = 6


#### Caso multidimensional

A la hora de acceder a elementos de un array multidimensional, tendremos que empezar indicando el índice del elemento en el nivel menos profundo y acabar indicando el índice del elemento en en nivel más profundo, todos entre `[]` separados por comas.

En el caso de un array bidimiensional, como el que se muestra a continuación,

In [11]:
a = np.array([[-10, -9], [7, 8]])
a.ndim

2

In [12]:
a

array([[-10,  -9],
       [  7,   8]])

Para acceder al elemento -9, primero habrá que indicar el índice 0, pues el array unidimensional al que pertenece se encuentra en el índice 0 del nivel menos profundo. A continuación, indicaremos el índice 1, pues esa es la posición que ocupa el elemento de nuestro interés dentro del array unidimensional, que se trata del nivel más profundo en este caso:

In [16]:
a[0, 0]

-10

En el caso de un array tridimensional, como el que se muestra a continuación,

In [17]:
a = np.array([[[1, 2, 3], [-3, -2, -1]], [[4, 5, 6], [7, 8, 9]]])
a.ndim

3

Para acceder al elemento 7, primero habrá que indicar el índice 1, pues el array 2-dimensional al que pertenece se encuentra en la posición 1 del nivel menos profundo. Entramos en el siguiente nivel, el array 2-dimensional. Ahora, la posición que hay que indicar es la 1, pues el array 1-dimensional ocupa dicho índice dentro del array 2-dimensional. Finalmente, llegamos al nivel más profundo, el array 1-dimensional, y ahora hay que indicar el índice 0, pues esa es la posición que ocupa el elemento de nuestro interés dentro del array unidimensional.

In [19]:
a[0, 0, 1]

2

Dado un array multidimensional, si lo que queremos es que se nos devuelva un array de dimensión menor, entonces solamnente tenemos que indicar sus índices tal cuál hacíamos para obtener un elemento.

Dado el array `a` tridimensional anterior, si queremos acceder al array unidimensional `[-3, -2, -1]`, entonces indicaremos entre `[]` los índices 0 y, a continuación, 1. Pues dicho array se encuentra en el primer array bidimensional y dentro de éste, ocupa la segunda posición, es decir, el índice 1:

In [ ]:
a[0, 1]

#### Índices negativos

Al igual que para el caso de las listas, los elementos de los `ndarrays` también pueden ser accedidos mediante índices negativos. 

El índice `-1` hace referencia al último elemento; el `-2`, al penúltimo; el `-3` al antepenúltimo; y así sucesivamente.

In [ ]:
a[-1]

### Slicing

En `Python`, **slicing** hace referencia a tomar elementos desde un índice dado hasta otro proporcionado.

Ya conocemos la sintaxis:

* `[inicio:fin]` donde iremos desde el índice `inicio` hasta el índice `fin`-1, y lo haremos de 1 en 1
* `[inicio:fin:paso]` donde iremos desde el índice `inicio` hasta el índice `fin`-1, y lo haremos de `paso` en `paso`



#### Caso unidimensional

In [21]:
# Array unidimensional
a1 = np.array([9, 8, 7, 6, 5, 4, 3])
a1

array([9, 8, 7, 6, 5, 4, 3])

In [22]:
# Del segundo elemento al cuarto de 1 en 1
a1[1:4]

array([8, 7, 6])

In [25]:
# Del primer elemento al sexto de 1 en 1
a1[:6]

array([9, 8, 7, 6, 5, 4])

In [26]:
# Del tercer elemento al último de 1 en 1
a1[2:]

array([7, 6, 5, 4, 3])

In [27]:
# Del segundo elemento al sexto de 2 en 2
a1[1:6:2]

array([8, 6, 4])

In [28]:
# Del primer elemento al quinto de 2 en 2
a1[:5:2]

array([9, 7, 5])

In [29]:
# Del segundo elemento al último de 3 en 3
a1[2::3]

array([7, 4])

In [30]:
# Del primer elemento al último de 4 en 4
a1[::4]

array([9, 5])

### Filtrando arrays

Filtrar un array implica la selección de elementos de un array existente que satisfagan una condición y crear un nuevo array con dichos elementos.

La sintaxis es muy similar al slicing, pero en vez de eso, entre corchetes indicamos una condición booleana. Los elementos que satisfagan la condición serán los que permanezcan, mientras que el resto serán omitidos.

Visto de otro modo, la condición crea un array booleano. Aquellas posiciones ocupadas por un `True` serán las contenidas en el array filtrado, mientras que las que estén ocupadas por `False` (porque no satisfacen la condición), serán descartadas.

In [31]:
a = np.array([4, 3, 2, 3, 4])
b = a[a == 4]
print(b)

[4 4]


In [32]:
a == 4

array([ True, False, False, False,  True])

In [33]:
c = a[a % 2 == 0]
print(c)

[4 2 4]


In [34]:
d = a[a <= 2]
print(d)

[2]


### Arrays y bucles

Podemos iterar un array tal cual lo hacíamos con listas:

#### Array 1D

In [35]:
d1 = np.array(["a", "b", "c"])

for i in d1:
  print(i)

a
b
c


#### Array 2D

In [36]:
d2 = np.array([["a", "b", "c"], [1, 2, 3]])

In [37]:
# Imprimimos los elementos del array 2D
for i in d2:
  print(i)

['a' 'b' 'c']
['1' '2' '3']


In [38]:
# Imprimimos los elementos de los arrays 1D
for d1 in d2:
  for i in d1:
    print(i)

a
b
c
1
2
3


#### Array 3D

In [39]:
d3 = np.array([["a", "b", "c"], [1, 2, 3],[4,5,6]])

In [40]:
# Imprimimos los elementos del array 3D
for d2 in d3:
  print(d2)

['a' 'b' 'c']
['1' '2' '3']
['4' '5' '6']


In [41]:
# Imprimimos los elementos de los arrays 2D
for d2 in d3:
  for d1 in d2:
    print(d1)

a
b
c
1
2
3
4
5
6


In [42]:
# Imprimimos los elementos de los arrays 1D
for d2 in d3:
  for d1 in d2:
    for i in d1:
      print(i)

a
b
c
1
2
3
4
5
6


Como vemos, cada vez que aumentamos la dimensión del array, hay que anidar bucles `for` para imprimir cada uno de los elementos de los arrays 1D,  pero dado un array con dimensión suficientemente grande este proceso se vuelve tedioso

Como alternativa podríamos hacer un reshape del array multidimensional a un array unidimensional

In [43]:
for i in d3.reshape(-1):
  print(i)

a
b
c
1
2
3
4
5
6


#### El método `.nditer()`

Otra alternativa para evitarnos tantas líneas de código y tanto coste computacional (reshape), tenemos el método `.nditer()`, que nos crea un iterable el cual nos permite imprimir todos los elementos de los arrays 1D, tal cuál hemos estado obteniendo hasta ahora:

In [44]:
for i in np.nditer(d3):
  print(i)

a
b
c
1
2
3
4
5
6


#### El método `.ndenumerate()`

A veces necesitamos el índice correspondiente al elemento durante la iteración. El método `.ndenumerate()` nos proporciona dicha información.



In [46]:
d1 = np.array(["a", "b", "c"])

for idx, i in np.ndenumerate(d1):
  print("Índice:", idx,"Elemento:", i)

Índice: (0,) Elemento: a
Índice: (1,) Elemento: b
Índice: (2,) Elemento: c


In [47]:
d2 = np.array([[1, 2], [3, 4], [5, 6]])

for idx, i in np.ndenumerate(d2):
  print("Índice:", idx,"Elemento:", i)

Índice: (0, 0) Elemento: 1
Índice: (0, 1) Elemento: 2
Índice: (1, 0) Elemento: 3
Índice: (1, 1) Elemento: 4
Índice: (2, 0) Elemento: 5
Índice: (2, 1) Elemento: 6


In [48]:
d3 = np.array([[["a", "b", "c", "d"], ["e", "f", "g", "h"]], [[1, 2, 3, 4], [5, 6, 7, 8]]])

for idx, i in np.ndenumerate(d3):
  print("Índice:", idx,"Elemento:", i)

Índice: (0, 0, 0) Elemento: a
Índice: (0, 0, 1) Elemento: b
Índice: (0, 0, 2) Elemento: c
Índice: (0, 0, 3) Elemento: d
Índice: (0, 1, 0) Elemento: e
Índice: (0, 1, 1) Elemento: f
Índice: (0, 1, 2) Elemento: g
Índice: (0, 1, 3) Elemento: h
Índice: (1, 0, 0) Elemento: 1
Índice: (1, 0, 1) Elemento: 2
Índice: (1, 0, 2) Elemento: 3
Índice: (1, 0, 3) Elemento: 4
Índice: (1, 1, 0) Elemento: 5
Índice: (1, 1, 1) Elemento: 6
Índice: (1, 1, 2) Elemento: 7
Índice: (1, 1, 3) Elemento: 8


### Concatenación de arrays

Para concatenar arrays, es decir, juntar dos o más arrays en un único array, usamos el método `.concatenate()`

In [49]:
# Conatenamos arrays 1D
a1 = np.array([-3, -2, -1])
a2 = np.array([1, 2, 3])
a = np.concatenate((a1, a2))
print(a)

[-3 -2 -1  1  2  3]


In [54]:
# Concatenamos arrays 2D
b1 = np.array([[-6, -5], [-4, -3], [-2, -1]])
b2 = np.array([[1, 2], [3, 4], [5, 6]])
print(b1)
# Con axis = 0
b = np.concatenate((b1, b2), axis = 0)
print("axis = 0 nos devuelve\n", b)

# Con axis = 1
b = np.concatenate((b1, b2), axis = 1)
print("\naxis = 1 nos devuelve\n", b)

[[-6 -5]
 [-4 -3]
 [-2 -1]]
axis = 0 nos devuelve
 [[-6 -5]
 [-4 -3]
 [-2 -1]
 [ 1  2]
 [ 3  4]
 [ 5  6]]

axis = 1 nos devuelve
 [[-6 -5  1  2]
 [-4 -3  3  4]
 [-2 -1  5  6]]


### Buscando elementos en un array

Podemos buscar elementos en concreto de un array con el método `.where()` que nos devolverá un array de índices en los cuales se encuentra el elemento que estamos buscando.

Por ejemplo, dado el siguiente array 1D `x`, busquemos en qué posiciones éste toma el valor 0. 

In [55]:
x = np.array([1, 0, -1, 0, 2, 0, -2, 0])
idx0 = np.where(x == 0) 

print(idx0)

(array([1, 3, 5, 7], dtype=int64),)


Como resultado hemos obtenido que en los índices 1, 3, 5 y 7 del array `x` se toma el valor 0.

**Observación.** Podemos poner cualquier tipo de condición a modo de argumento del método `.where()`.

Dado el siguiente array 1D `y`, busquemos en qué índices se toman valores pares.

In [84]:
y = np.array([2, 3, 6, 7, 14, 15, 30, 31])
z = np.where(y % 2 == 0)

print(z)

(array([0, 2, 4, 6], dtype=int64),)


### Ordenando arrays

Ordenar arrays implica reordenar los elementos siguiendo una secuencia ordenada.

A su vez, una secuencia ordenada es cualquier sucesión que tiene un orden ciuos elementos siguen, como por ejemplo el orden alfabético o numérico, tanto ascendente como descendente.

Para ordenar los elementos de un array, disponemos del método `.sort()`

In [85]:
x = np.array(["c", "m", "k", "z", "a"])
print(np.sort(x))

['a' 'c' 'k' 'm' 'z']


In [86]:
x = np.array(["caracol", "mariposa", "escarabajo", "perezoso", "armadillo"])
print(np.sort(x))

['armadillo' 'caracol' 'escarabajo' 'mariposa' 'perezoso']


In [87]:
x = np.array([2, -2, 5, -5, 10, -10, 0])
print(np.sort(x))

[-10  -5  -2   0   2   5  10]


In [88]:
x = np.array([2.5, -2.3, 5.1, -5.7, 10.9, -10.6, 0.4])
print(np.sort(x))

[-10.6  -5.7  -2.3   0.4   2.5   5.1  10.9]


In [89]:
x = np.array([True, False, True, False])
print(np.sort(x))

[False False  True  True]


---

De manera similar a como se hacía con range, NumPy también cuenta con un método que permite crear un array con un rango de elementos.np.arange()

In [92]:
a = np.arange(10)
b = np.arange(1, 11)
c = np.arange(0, 11, 2)

print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]


In [93]:
print(list(range(10)))  
print(list(range(1, 11)))
print(list(range(0, 11, 2)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 2, 4, 6, 8, 10]


También se podría usar np.linspace() para crerar un array con valores que están espacias en un intervalo establecido.

El primer y segundo parámetro indicar el primer y último elemento del array respectivamente mientras que el tercer parámetro indica la cantidad de elementos que tendrá el array.

In [111]:
a = np.linspace(0,100, num = 201)
print(a)

[  0.    0.5   1.    1.5   2.    2.5   3.    3.5   4.    4.5   5.    5.5
   6.    6.5   7.    7.5   8.    8.5   9.    9.5  10.   10.5  11.   11.5
  12.   12.5  13.   13.5  14.   14.5  15.   15.5  16.   16.5  17.   17.5
  18.   18.5  19.   19.5  20.   20.5  21.   21.5  22.   22.5  23.   23.5
  24.   24.5  25.   25.5  26.   26.5  27.   27.5  28.   28.5  29.   29.5
  30.   30.5  31.   31.5  32.   32.5  33.   33.5  34.   34.5  35.   35.5
  36.   36.5  37.   37.5  38.   38.5  39.   39.5  40.   40.5  41.   41.5
  42.   42.5  43.   43.5  44.   44.5  45.   45.5  46.   46.5  47.   47.5
  48.   48.5  49.   49.5  50.   50.5  51.   51.5  52.   52.5  53.   53.5
  54.   54.5  55.   55.5  56.   56.5  57.   57.5  58.   58.5  59.   59.5
  60.   60.5  61.   61.5  62.   62.5  63.   63.5  64.   64.5  65.   65.5
  66.   66.5  67.   67.5  68.   68.5  69.   69.5  70.   70.5  71.   71.5
  72.   72.5  73.   73.5  74.   74.5  75.   75.5  76.   76.5  77.   77.5
  78.   78.5  79.   79.5  80.   80.5  81.   81.5  8

In [113]:
c = np.arange(0, 100.5, 0.5)
print(c)


[  0.    0.5   1.    1.5   2.    2.5   3.    3.5   4.    4.5   5.    5.5
   6.    6.5   7.    7.5   8.    8.5   9.    9.5  10.   10.5  11.   11.5
  12.   12.5  13.   13.5  14.   14.5  15.   15.5  16.   16.5  17.   17.5
  18.   18.5  19.   19.5  20.   20.5  21.   21.5  22.   22.5  23.   23.5
  24.   24.5  25.   25.5  26.   26.5  27.   27.5  28.   28.5  29.   29.5
  30.   30.5  31.   31.5  32.   32.5  33.   33.5  34.   34.5  35.   35.5
  36.   36.5  37.   37.5  38.   38.5  39.   39.5  40.   40.5  41.   41.5
  42.   42.5  43.   43.5  44.   44.5  45.   45.5  46.   46.5  47.   47.5
  48.   48.5  49.   49.5  50.   50.5  51.   51.5  52.   52.5  53.   53.5
  54.   54.5  55.   55.5  56.   56.5  57.   57.5  58.   58.5  59.   59.5
  60.   60.5  61.   61.5  62.   62.5  63.   63.5  64.   64.5  65.   65.5
  66.   66.5  67.   67.5  68.   68.5  69.   69.5  70.   70.5  71.   71.5
  72.   72.5  73.   73.5  74.   74.5  75.   75.5  76.   76.5  77.   77.5
  78.   78.5  79.   79.5  80.   80.5  81.   81.5  8

### Elementos aleatorios en `numpy`

**Número aleatorio.** Un número aleatorio singifica que se trata de un número que no puede ser predicho lógicamente.

**¡Cuidado!** No hay que confundir número aleatorio con que se genere un número diferente cada vez que ejecutemos.

Como los ordenadores trabajan mediante algoritmos, un programa destinado a generar números aleatorios implica que los números no serán realmente aleatorios. Los números aleatorios generados mediante un algoritmo son conocidos como **números pseudoaleatorios**.

En este apartado trabajaremos con números pseudoaleatorios y veremos como generarlos.



#### El módulo `random`

`numpy` tiene el módulo `random` dedicado a trabajar con números aleatorios

Para generar números enteros aleatorios, usamos el método `.randint()`


In [115]:
from numpy import random

In [129]:
# Generamos un número entero aleatorio del 1 al 20
n = random.randint(1, 20)
print(n)

12


In [142]:
# Generamos un número entero aleatorio del 0 al 10
m = random.randint(10)
print(m)

6


Para generar números reales aleatorios dentro del intervalo $[0, 1]$, usamos el método `.rand()`

In [211]:
# Generamos un número real aleatorio entre el 0 y el 1
x = random.rand()
print(x)

0.9582654491680295


#### Arrays aleatorios

Podemos generar arrays aleatorios tanto con el método `.randint()` como con el método `.rand()`

In [218]:
# Generamos un array 1D de 5 elementos enteros aleatorios
a = random.randint(100, size = 5)
print(a)

[77 32 24 31 50]


In [230]:
a = random.randint(50, 100, size = 5)
print(a)

[65 91 86 90 90]


In [254]:
# Generamos un array 1D de 3 elementos reales aleatorios
b = random.rand(3)
print(b)

[0.62801946 0.46974226 0.42933373]


In [303]:
# Generamos un array 2D de 5 arrays 1D cada uno con 4 enteros aleatorios
c = random.randint(50, size = (5, 4))
print(c)

[[31 13 44 25]
 [34 33  9 15]
 [ 9 38 43 25]
 [ 3 44 43 15]
 [42  0 17 45]]


In [336]:
# Generamos un array 3D de 2 arrays 2D cada uno con 4 arrays 1D
#   cada uno con 3 reales aleatorios
d = random.rand(2, 4, 3)
print(d)

[[[0.50035412 0.39612592 0.22690447]
  [0.10980757 0.11949833 0.89952319]
  [0.73522563 0.94663065 0.83105085]
  [0.47577977 0.28790333 0.8481363 ]]

 [[0.85503373 0.27071951 0.31260277]
  [0.62917433 0.89422595 0.12885321]
  [0.85610162 0.944144   0.97690381]
  [0.61878291 0.95710768 0.73790162]]]


#### Elegir un elemento aleatorio de un array

Dado un array, podemos elegir aleatoriamente un elemento suyo con el método `.choice()`

In [343]:
x = np.array([1, 2, 3, 4, 5, -5, -4, -3, -2, -1])
print(random.choice(x))

5


El método `.choice()` también consta del parámetro `size`, con lo cual podemos generar un array aleatorio con los elementos de un array dado:

In [344]:
print(random.choice(x, size = (3, 6)))

[[ 2 -2  1 -2 -1  4]
 [-3 -3  2 -2 -3 -2]
 [-3 -1  2  5  5  5]]


**¡Cuidado!** El método `.choice()` solamente toma como parámetro arrays unidimensionales

Existe otro parámetro del método `.choice()` que nos permite modificar las probabilidades de cada elemento. Éste es el parámetro `p`, al que le tendremos que proporcionar una lista de probabilidades (todos los elementos deben ser menores o iguales a 1 y la suma de todos ellos debe ser 1).

**Observación.** Por defecto, todos los elementos son equiprobables, es decir, tienen la misma probabilidad que es $\frac{1}{n}$, siendo $n$ el número de elementos del array.

In [345]:
x = np.array([1, 2, 3, 4, 5, -5, -4, -3, -2, -1])
print(random.choice(x, 
                    p = [0.2, 0.2, 0.05, 0.05, 0.05, 0.05, 0.1, 0.1, 0.05, 0.15],
                    size = (2, 6)))

[[ 2  1 -5  5 -1  2]
 [-1  5 -3 -4  2 -3]]


se ha generado un array 2D con 2 arrays 1D cada uno con 6 elementos, donde las probabilidades para los elementos del array original son:

* Los elementos `1` y `2` tienen probabilidad 0.2 de salir
* El elemento `-1` tiene probabilidad 0.15
* Los elementos `-4` y `-3` tienen probabilidad 0.1 de salir
* Los elementos `3`, `4`, `5`, `6` y `-2` tienen probabilidad 0.05

Todas las probabilidades se encuentran en el intervalo $[0, 1]$ y si las sumamos dan 1.

#### Permutaciones aleatorias

**Permutación.** Una permutación de un array se refiere a la reordenación de sus elementos.

El módulo `random` de `numpy` nos proporciona dos métodos para crear permutaciones aleatorias de un array dado:

* `.shuffle()` modifica el array original
* `.permutation()` que crea una copia


In [368]:
a = np.array([1, 2, 3, 4])
random.shuffle(a)

print("Array original permutado:", a)

Array original permutado: [4 1 2 3]


In [369]:
a = np.array([1, 2, 3, 4])
b = random.permutation(a)

print("Array original permutado:", b)
print("Array original:", a)

Array original permutado: [2 4 1 3]
Array original: [1 2 3 4]


### Funciones universales

Las funciones universales son aquellas que operan sobre el objeto ndarray

Podemos comprobar si un método se trata de una función universal con la función `type`. Cuando se trata de una función universal, obtenemos que es de tipo `np.ufunc`

In [370]:
# Es una función universal
print(type(np.multiply))

<class 'numpy.ufunc'>


In [371]:
type(np.multiply) == np.ufunc

True

In [372]:
# No es una función universal
print(type(np.concatenate))

<class 'function'>


In [373]:
type(np.concatenate) == np.ufunc

False

#### Aritmética

In [374]:
a = np.array([12, 0, 7])
b = np.array([8, 2, 5])

El método `.add()` suma arrays elemento a elemento

In [375]:
print(np.add(a, b))

[20  2 12]


El método `.subtract()` resta arrays elemento a elemento


In [376]:
print(np.subtract(a, b))

[ 4 -2  2]


El método `.multiply()` multiplica arrays elemento a elemento

In [377]:
print(np.multiply(a, b))

[96  0 35]


El método `.divide()` divide arrays elemento a elemento

In [378]:
print(np.divide(a, b))

[1.5 0.  1.4]


El método `.power()` calcula la potencia del primer array elevado al segundo elemento a elemento 

In [379]:
print(np.power(a, b))

[429981696         0     16807]


Tanto el método `.mod()` como el método `.remainder()` calculan el resto de la división entera del primer array entre el segundo, elemento a elemento

In [380]:
print(np.mod(a, b))
print(np.remainder(a, b))

[4 0 2]
[4 0 2]


El método `.divmod()` devuelve una tupla con 2 arrays, el primero contiene los cocientes y el segundo los restos de las divisiones enteras elemento a elemento 

In [381]:
print(np.divmod(a, b))

(array([1, 0, 1]), array([4, 0, 2]))


El método `.absolute()` devuelve el valor absoluto de cada elemento de un array

In [382]:
print(np.absolute(np.array([-1, 0, -2, 1, 2])))

[1 0 2 1 2]


#### Redondeando decimales

En `numpy` tenemos 5 formas de redondear los decimales de un número

* `.trunc()` para truncar
* `.fix()` también para truncar
* `.round()` para redondear
* `.floor()` para redondear a la baja
* `.ceil()` para redondear a la alza

In [389]:
a = np.array([-5.1777, 5.7778, 5.5134])   

In [385]:
print("Si truncamos con .trunc(), obtendremos {}".format(np.trunc(a)))
print("Si truncamos con .fix(), obtendremos {}".format(np.fix(a)))

Si truncamos con .trunc(), obtendremos [-5.  5.  5.]
Si truncamos con .fix(), obtendremos [-5.  5.  5.]


In [390]:
print("Si rendondeamos con .around(), obtendremos {}".format(np.around(a)))

Si rendondeamos con .around(), obtendremos [-5.  6.  6.]


**Observación.** Como segundo parámetro, podemos indicar a cuántas cifras decimales queremos redondear

In [391]:
print("Si rendondeamos con .round() a 3 cifras decimales, obtendremos {}".
      format(np.round(a, 3)))

Si rendondeamos con .round() a 3 cifras decimales, obtendremos [-5.178  5.778  5.513]


In [392]:
print("Si rendondeamos a la baja con .floor(), obtendremos {}".format(np.floor(a)))

Si rendondeamos a la baja con .floor(), obtendremos [-6.  5.  5.]


In [393]:
print("Si rendondeamos con a la alza .ceil(), obtendremos {}".format(np.ceil(a)))

Si rendondeamos con a la alza .ceil(), obtendremos [-5.  6.  6.]


#### Sumas y Diferencias

Ya concoemos el método `.add()` que dados dos arrays los suma elemento a elemento

In [396]:
x = np.array([2, 3, 7])
y = np.array([-1, 5, 0])

In [397]:
print(np.add(x, y))

[1 8 7]


El método `.sum()` nos calcula la suma de los elementos de un array

In [398]:
print("La suma de los elementos de x es", np.sum(x))
print("La suma de los elementos de y es", np.sum(y))

La suma de los elementos de x es 12
La suma de los elementos de y es 4


Para calcular la suma acumulada de los elementos de un array, disponemos del método `.cumsum()`

In [399]:
print("La suma acumulada de los elementos de x es", np.cumsum(x))
print("La suma acumulada de los elementos de y es", np.cumsum(y))

La suma acumulada de los elementos de x es [ 2  5 12]
La suma acumulada de los elementos de y es [-1  4  4]


Para calcular las diferencias entre los elementos de un array, disponemos del método `.diff()`

In [401]:
print("La diferencia de elementos sucesivos de x es", np.diff(x))
print("La diferencia de elementos sucesivos de y es", np.diff(y))

La diferencia de elementos sucesivos de x es [1 4]
La diferencia de elementos sucesivos de y es [ 6 -5]


El parámetro `n` nos permite elegir cuántas veces queremos calcular la diferencia entre los elementos sucesivos de un array:

In [402]:
print("x =", x)
print("Realizando la diferencia entre sus elementos sucesivos obtenemos", np.diff(x))
print("Realizando 2 veces la diferencia entre sus elementos sucesivos obtenemos", np.diff(x, n = 2))

x = [2 3 7]
Realizando la diferencia entre sus elementos sucesivos obtenemos [1 4]
Realizando 2 veces la diferencia entre sus elementos sucesivos obtenemos [3]


In [403]:
print("y =", y)
print("Realizando la diferencia entre sus elementos sucesivos obtenemos", np.diff(y))
print("Realizando 2 veces la diferencia entre sus elementos sucesivos obtenemos", np.diff(y, n = 2))

y = [-1  5  0]
Realizando la diferencia entre sus elementos sucesivos obtenemos [ 6 -5]
Realizando 2 veces la diferencia entre sus elementos sucesivos obtenemos [-11]


#### Productos

El método `.prod()` calcula el producto de los elementos de un array

In [404]:
a = np.array([2, 4, 6, 8])
np.prod(a)

384

Con el método `.cumprod()` podemos calcular el producto acumulado de un array

In [406]:
a = np.array([2, 4, 6, 8])
np.cumprod(a)

array([  2,   8,  48, 384])

#### Trigonometría

En `numpy` el número $\pi$ se obtiene con `np.pi`.

En `numpy` disponemos de los métodos:

* `.sin()`
* `.cos()`
* `.tan()`

para calcular el seno, coseno y tangente de los elementos de un array (los valores se consideran en radianes)

* `.deg2rad()`
* `.rad2deg()`

para calcular conversión de ángulos a radianes y de radianes a ángulos respectivamente

* `.arcsin()`
* `.arccos()`
* `.arctan()`

para calcular el arcoseno, arcocoseno y arcotangente y hallar ángulos (el resultado es devuelto en radianes)

#### Funciones hiperbólicas

En `numpy` disponemos de los métodos:

* `.sinh()`
* `.cosh()`
* `.tanh()`

para calcular el seno, coseno y tangente hiperbólicos de los elementos de un array (los valores se consideran en radianes)

* `.arcsinh()`
* `.arccosh()`
* `.arctanh()`

para calcular el arcoseno, arcocoseno y arcotangente hiperbólicos y hallar ángulos (el resultado es devuelto en radianes)

#### Conjuntos en `numpy`

Para crear un conjunto a partir de un array, usamos el método `.unique()`:  

In [409]:
a = np.array([1, 2, -1, 1, 5, 6, 2, 4, -1, 2])
set_a = np.unique(a)
print(set_a)

[-1  1  2  4  5  6]


unión entre dos arrays 1D, usamos el método `.union1d()`

In [411]:
x = np.array([1, 2, 3, 4])
y = np.array([-2, -1, 0, 1])
print(np.union1d(x, y))

[-2 -1  0  1  2  3  4]


Para hallar la intersección entre dos arrays 1D, usamos el método `.intersect1d()` 

In [412]:
print(np.intersect1d(x, y))

[1]


Para hallar la diferencia entre dos arrays 1D, disponemos del método `.setdiff1d()`

In [414]:
print(np.setdiff1d(x, y))
print(np.setdiff1d(y, x))

[2 3 4]
[-2 -1  0]


Para hallar la diferencia simétrica entre dos arrays 1D, usamos el método `.setxor1d()`

In [416]:
print(np.setxor1d(x, y))

[-2 -1  0  2  3  4]
